feat(mojaloop/#3436): nodejs upgrade
mojaloop/als-oracle-pathfinder pull request #85
Opened 2023-12-13 00:12 UTC by aaronreynoza

2023-12-14 08:22 UTC, geka-evk commented on src/server.js
> +    console.log('Server stopped')
Why do we use  _console.log_ here, and not Logger?

2023-12-14 08:23 UTC, geka-evk commented on Dockerfile
> +#    -t mojaloop/sdk-scheme-adapter:local \
Maybe, it's better to update image name according repository name?

2023-12-14 17:12 UTC, geka-evk approved these changes

2023-12-18 09:15 UTC, oderayi requested changes
Looking good.

- Please do snapshot release to validate the release pipeline.

2023-12-18 09:15 UTC, oderayi commented on .circleci/config.yml
> +      #           - /bugfix*/
This can be removed until we have integration and functional tests.

2023-12-18 09:15 UTC, oderayi commented on .circleci/config.yml
> +            # - test-functional
Can be removed.

2023-12-18 09:15 UTC, oderayi commented on src/server.js
> +module.exports.stopServer = async function (server) {
Thanks for adding this and the test.

2023-12-19 07:29 UTC, oderayi approved these changes

2023-12-20 07:04 UTC, merged